// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Attachment struct {
	ID               int64     `json:"attachmentId"`
	TodoID           int64     `json:"todoId"`
	OriginalFilename string    `json:"originalFilename"`
	StorageFilename  string    `json:"storageFilename"`
	CreatedAt        time.Time `json:"createdAt"`
}

type Todo struct {
	ID        int64     `json:"todoId"`
	Title     string    `json:"title"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	FileCount int32     `json:"fileCount"`
}
