// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: todo.sql

package db

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    title
) VALUES (
    $1
) RETURNING id, title, status, created_at, file_count, owner
`

func (q *Queries) CreateTodo(ctx context.Context, title string) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.FileCount,
		&i.Owner,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, status, created_at, file_count, owner FROM todos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.FileCount,
		&i.Owner,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, status, created_at, file_count, owner FROM todos
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListTodosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.FileCount,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoFileCount = `-- name: UpdateTodoFileCount :one
UPDATE todos
SET file_count = file_count + $2
WHERE id = $1
RETURNING id, title, status, created_at, file_count, owner
`

type UpdateTodoFileCountParams struct {
	ID        int64 `json:"todoId"`
	FileCount int32 `json:"fileCount"`
}

func (q *Queries) UpdateTodoFileCount(ctx context.Context, arg UpdateTodoFileCountParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodoFileCount, arg.ID, arg.FileCount)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.FileCount,
		&i.Owner,
	)
	return i, err
}

const updateTodoTitleStatus = `-- name: UpdateTodoTitleStatus :one
UPDATE todos
SET title = COALESCE($2, title),
    status = COALESCE($3, status)
WHERE id = $1
RETURNING id, title, status, created_at, file_count, owner
`

type UpdateTodoTitleStatusParams struct {
	ID     int64   `json:"todoId"`
	Title  *string `json:"title"`
	Status *string `json:"status"`
}

func (q *Queries) UpdateTodoTitleStatus(ctx context.Context, arg UpdateTodoTitleStatusParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodoTitleStatus, arg.ID, arg.Title, arg.Status)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.FileCount,
		&i.Owner,
	)
	return i, err
}
